### ISSUE TITLE
Add all LF Energy Projects

### ISSUE THREAD

**Issue by stv0g** [oss-in-energy/oss-in-energy#14]
https://www.lfenergy.org/projects/

- [x] CoMPAS
- [x] Grid eXchange Fabric
- [x] PowSyBl
- [x] OperatorFabric
- [x] RIAPS
- [ ] Energy Market Methods Consortium
- [x] OpenEEMeter
- [x] openLEADR
- [x] SEAPATH
- [x] HYPHAE
- [x] SOGNO
- [ ] FledgePOWER

**Comment by fwege** [comment]
Further projects added with 2ad69f3adb15cb844ce9df040be0b8aa93
For the missing projects I could not find a proper tool or repository.
