### ISSUE TITLE
Add all Grid Protection Alliance (GPA) projects

### ISSUE THREAD

**Issue by stv0g** [oss-in-energy/oss-in-energy#21]
https://github.com/GridProtectionAlliance

- [x] [OpenHistorian](https://github.com/GridProtectionAlliance/openHistorian)
- [x] [gsf](https://github.com/GridProtectionAlliance/gsf)
- [x] [OpenPDC](https://github.com/GridProtectionAlliance/openPDC)
- [ ] ... lots more on their GitHub page

**Comment by fwege** [comment]
Added pinned repositories in d5e7f9114cfd27118adbb28b627be12e628ff941

**Comment by fwege** [comment]
Mentioned projects as well as all pinned projects were added.
For further additions please help us with a PR.
